### ISSUE TITLE
warrior / talent  [Double Time] issue.

### ISSUE THREAD

**Issue by reporter111** [Artamedes/WarspringTesting#1]
**Description**: Description of the problem.
seems warrior  [Double Time] is bugged and need fix .
the talent must grant you 2 charge casts .visually it gives you but when i try to use the charge spell again it wont let me use it until 20 second cooldown ends.

**Priority**: Low, med or High?
medium i think !

**Current behaviour**: What happens
nothing will happen after you get the talent .just visual that say you have 2 charge of charge spell .

**Expected behaviour**: What should happen instead
it must let you charge twice .instead of once per 20 sec .

**Steps to reproduce the problem**:

1.  -
2.  -
3.  -

**Screenshots**: Screenshots

**Comment by Artamedes** [comment]
fixed in new core
