### ISSUE TITLE
DK:  Pet - Gargoyle

### ISSUE THREAD

**Issue by crysisDz** [Artamedes/WarspringTesting#10]
****Description**:**  Pet Gargoyle  not working

Priority: Low,

****Current behaviour**:** when summon Gargoyle  he stay and do nothing,  not attacking target no spell to use.

****Expected behaviour**:** he should attack my target ** A Gargoyle flies into the area and bombards the target for 40 sec.**
![screenshot_2](https://user-images.githubusercontent.com/40612917/41987498-6c0c2236-7a20-11e8-99cf-00898b267da7.png)

**Comment by Artamedes** [comment]
fixed in new core
