### ISSUE TITLE
Rogue Stealth bugged

### ISSUE THREAD

**Issue by reporter111** [Artamedes/WarspringTesting#3]
**Description**: Description of the problem.
when player use stealth and do any action that make stealth cancel /attack etc ./force cancel stealth
the spell become non-usable anymore just usable after reloag .

**Priority**: Low, med or High?
high

**Current behaviour**: What happens
-

**Expected behaviour**: What should happen instead
-
**Steps to reproduce the problem**:

1.  -  
2.  - 
3.  -

**Screenshots**: Screenshots

**Comment by Artamedes** [comment]
fixed next core update tonight
