### ISSUE TITLE
Warlock  : [Demonic Circle: Teleport]

### ISSUE THREAD

**Issue by crysisDz** [Artamedes/WarspringTesting#6]
**Description :** Demonic Circle: teleport  can't use 

****Priority**:** Low,

**Current behavior**: when use  [Demonic Circle: Summon]  then   try to use  [Demonic Circle: teleport ] dint work  and  tell u "  You can't do  that" ,  it's like not available spell.

****Expected behavior**:  The  [Demonic Circle: Teleport]  should port you back to the area that u  Summoned  Demonic Circle on it.

****Screenshots**:** Screenshots
![screenshot_1](https://user-images.githubusercontent.com/40612917/41984429-d0649eb0-7a17-11e8-9d78-d3155b72ba5f.png)

**Comment by Artamedes** [comment]
fixed next update
