### ISSUE TITLE
Warlock Pets unknown

### ISSUE THREAD

**Issue by crysisDz** [Artamedes/WarspringTesting#7]
**Description**: All Pets with no name

**Priority**: Low,

**Current behavior**: All Pets have no name , when they should.

**Expected behaviour**: when summon pet should have his own name :  Imp-Voidwalker-Felhunter-Succubus

**Screenshots**: Screenshots
![screenshot_2](https://user-images.githubusercontent.com/40612917/41984845-d2276e0c-7a18-11e8-950d-8f602f018379.png)
![screenshot_3](https://user-images.githubusercontent.com/40612917/41984847-d2afcd24-7a18-11e8-8f61-10f58bff7879.png)

**Comment by Artamedes** [comment]
Fixed next update
