### ISSUE TITLE
DK: Death siphon

### ISSUE THREAD

**Issue by crysisDz** [Artamedes/WarspringTesting#8]
****Description**:**  Death siphon ; when try use say   : no enough Runes.

****Priority**:** High

Current behaviour: not working

****Expected behaviour**:** Tears at a target's soul, healing the Death Knight in proportion to the damage dealt

**Screenshots**: Screenshots
![screenshot_1](https://user-images.githubusercontent.com/40612917/41986105-4843a7b0-7a1c-11e8-80c8-76395f56fedf.png)

**Comment by Artamedes** [comment]
fixed in new core
